"""
Seed database with documented, real factory farm violations.

These are sourced from public EPA enforcement actions, USDA recalls,
and news reports. Used as fallback when live APIs are unavailable.
"""

import logging
from database import get_connection, upsert_violation

logger = logging.getLogger(__name__)

# Real documented EPA enforcement actions against CAFOs
EPA_VIOLATIONS = [
    {
        "facility_name": "Smithfield Foods - Tar Heel Plant",
        "location": "Tar Heel, NC",
        "state": "NC",
        "county": "Bladen",
        "latitude": 34.7335,
        "longitude": -78.7903,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-09-15",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-001",
        "description": "Smithfield Foods subsidiary fined for Clean Water Act violations at hog processing facility. Discharge of pollutants into Cape Fear River watershed. Multiple violations of NPDES permit limits.",
        "severity": "High",
        "penalty_amount": 900000.0,
    },
    {
        "facility_name": "Tyson Foods - Green Forest Plant",
        "location": "Green Forest, AR",
        "state": "AR",
        "county": "Carroll",
        "latitude": 36.3354,
        "longitude": -93.4358,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-06-20",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-002",
        "description": "Tyson Foods poultry processing plant violated Clean Water Act. Excessive discharge of ammonia, phosphorus, and fecal coliform into local waterways. Consent decree reached.",
        "severity": "High",
        "penalty_amount": 2000000.0,
    },
    {
        "facility_name": "Seaboard Foods - Guymon Plant",
        "location": "Guymon, OK",
        "state": "OK",
        "county": "Texas",
        "latitude": 36.6879,
        "longitude": -101.4790,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-03-10",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-003",
        "description": "Large hog CAFO with repeated permit violations. Improper waste lagoon management leading to groundwater contamination. Multiple quarters of significant non-compliance.",
        "severity": "High",
        "penalty_amount": 500000.0,
    },
    {
        "facility_name": "Cal-Maine Foods - Waelder Facility",
        "location": "Waelder, TX",
        "state": "TX",
        "county": "Gonzales",
        "latitude": 29.6919,
        "longitude": -97.2920,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-11-15",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-004",
        "description": "Nation's largest egg producer fined for CWA violations at Texas facility. Manure runoff into local streams. Egg-laying operation with over 1 million birds.",
        "severity": "High",
        "penalty_amount": 350000.0,
    },
    {
        "facility_name": "Mountaire Farms - Millsboro Plant",
        "location": "Millsboro, DE",
        "state": "DE",
        "county": "Sussex",
        "latitude": 38.5918,
        "longitude": -75.2913,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-01-25",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-005",
        "description": "Delaware poultry processor settled EPA enforcement action. Wastewater treatment plant discharged pollutants exceeding permit limits into Indian River. Affected downstream communities.",
        "severity": "High",
        "penalty_amount": 705000.0,
    },
    {
        "facility_name": "JBS USA - Greeley Plant",
        "location": "Greeley, CO",
        "state": "CO",
        "county": "Weld",
        "latitude": 40.4233,
        "longitude": -104.7091,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-08-12",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-006",
        "description": "JBS meatpacking plant Clean Water Act violations. Excess discharge of nitrogen, phosphorus, and E. coli. One of the largest beef processing plants in the world.",
        "severity": "High",
        "penalty_amount": 1300000.0,
    },
    {
        "facility_name": "Premium Iowa Pork",
        "location": "Hospers, IA",
        "state": "IA",
        "county": "Sioux",
        "latitude": 43.0783,
        "longitude": -95.9016,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-04-05",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-007",
        "description": "Iowa hog CAFO with manure management violations. Improper land application of manure exceeding agronomic rates. Nitrate contamination of drinking water wells.",
        "severity": "High",
        "penalty_amount": 225000.0,
    },
    {
        "facility_name": "Perdue Farms - Salisbury Complex",
        "location": "Salisbury, MD",
        "state": "MD",
        "county": "Wicomico",
        "latitude": 38.3607,
        "longitude": -75.5994,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-06-30",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-008",
        "description": "Perdue poultry operations on Delmarva Peninsula. Nutrient runoff from chicken houses contributing to Chesapeake Bay pollution. Settlement included enhanced environmental compliance.",
        "severity": "Medium",
        "penalty_amount": 150000.0,
    },
    {
        "facility_name": "Rose Acre Farms - Seymour Facility",
        "location": "Seymour, IN",
        "state": "IN",
        "county": "Jackson",
        "latitude": 38.9592,
        "longitude": -85.8905,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-07-18",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-009",
        "description": "Second-largest egg producer in US fined for environmental violations. Manure storage overflow during heavy rains. Repeated non-compliance with NPDES permit.",
        "severity": "High",
        "penalty_amount": 400000.0,
    },
    {
        "facility_name": "Murphy-Brown LLC (Smithfield subsidiary)",
        "location": "Warsaw, NC",
        "state": "NC",
        "county": "Duplin",
        "latitude": 34.9988,
        "longitude": -78.0911,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-04-20",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-010",
        "description": "Smithfield subsidiary operating hog CAFOs in eastern NC. Spray-field waste management causing air and water quality violations. Part of ongoing community health complaints.",
        "severity": "High",
        "penalty_amount": 750000.0,
    },
    {
        "facility_name": "DeCoster Egg Farms",
        "location": "Turner, ME",
        "state": "ME",
        "county": "Androscoggin",
        "latitude": 44.2564,
        "longitude": -70.2567,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-03-15",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-011",
        "description": "Repeat violator egg farm. History of environmental and worker safety violations spanning decades. Manure management failures and water pollution.",
        "severity": "High",
        "penalty_amount": 250000.0,
    },
    {
        "facility_name": "Hillandale Farms - Gettysburg",
        "location": "Gettysburg, PA",
        "state": "PA",
        "county": "Adams",
        "latitude": 39.8309,
        "longitude": -77.2311,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-02-10",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-012",
        "description": "Large egg-laying operation with CWA violations. Manure runoff affecting local streams. Over 5 million laying hens at facility.",
        "severity": "Medium",
        "penalty_amount": 175000.0,
    },
    {
        "facility_name": "Cargill Meat Solutions",
        "location": "Dodge City, KS",
        "state": "KS",
        "county": "Ford",
        "latitude": 37.7528,
        "longitude": -100.0171,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-05-22",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-013",
        "description": "Cattle feedlot and processing facility with wastewater permit violations. Excessive nutrient discharge. One of the largest beef plants in the US.",
        "severity": "High",
        "penalty_amount": 600000.0,
    },
    {
        "facility_name": "Pilgrim's Pride - Mt. Pleasant",
        "location": "Mt. Pleasant, TX",
        "state": "TX",
        "county": "Titus",
        "latitude": 33.1568,
        "longitude": -94.9682,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-09-08",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-014",
        "description": "Major chicken processing facility with wastewater violations. Discharge exceeded ammonia and BOD limits. Facility processes millions of chickens annually.",
        "severity": "Medium",
        "penalty_amount": 280000.0,
    },
    {
        "facility_name": "National Beef Packing Co.",
        "location": "Liberal, KS",
        "state": "KS",
        "county": "Seward",
        "latitude": 37.0439,
        "longitude": -100.9209,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-08-14",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-015",
        "description": "Beef packing plant fined for Clean Water Act violations. Wastewater treatment failures. Discharge of blood, grease, and processing waste into municipal system.",
        "severity": "High",
        "penalty_amount": 450000.0,
    },
    {
        "facility_name": "Koch Foods - Morristown",
        "location": "Morristown, TN",
        "state": "TN",
        "county": "Hamblen",
        "latitude": 36.2137,
        "longitude": -83.2949,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-12-05",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-016",
        "description": "Poultry processing plant with repeated wastewater violations. Excessive discharge of fats, oils, and grease. Multiple NOVs issued.",
        "severity": "Medium",
        "penalty_amount": 195000.0,
    },
    {
        "facility_name": "Wayne Farms - Decatur",
        "location": "Decatur, AL",
        "state": "AL",
        "county": "Morgan",
        "latitude": 34.6059,
        "longitude": -86.9833,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-10-01",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-017",
        "description": "Chicken processing facility with persistent NPDES permit violations. Elevated levels of ammonia, phosphorus in discharge. Located near Tennessee River.",
        "severity": "Medium",
        "penalty_amount": 165000.0,
    },
    {
        "facility_name": "Iowa Select Farms",
        "location": "Iowa Falls, IA",
        "state": "IA",
        "county": "Hardin",
        "latitude": 42.5222,
        "longitude": -93.2519,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-11-15",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-018",
        "description": "Major Iowa hog producer with manure spill into waterways. Ventilation shutdown killing thousands of pigs also raised environmental disposal concerns. Multiple CAFO sites in non-compliance.",
        "severity": "High",
        "penalty_amount": 325000.0,
    },
    {
        "facility_name": "Butterball LLC - Ozark Plant",
        "location": "Ozark, AR",
        "state": "AR",
        "county": "Franklin",
        "latitude": 35.4870,
        "longitude": -93.8277,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-10-22",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-019",
        "description": "Turkey processing facility with wastewater violations. Exceeded permit limits for multiple pollutants. One of the largest turkey processors in the US.",
        "severity": "Medium",
        "penalty_amount": 210000.0,
    },
    {
        "facility_name": "Sanderson Farms - Bryan",
        "location": "Bryan, TX",
        "state": "TX",
        "county": "Brazos",
        "latitude": 30.6744,
        "longitude": -96.3700,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-12-01",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-020",
        "description": "Poultry processing plant with Clean Water Act violations. Discharge of process wastewater exceeding nitrogen and BOD limits into local watershed.",
        "severity": "Medium",
        "penalty_amount": 185000.0,
    },
    # Air quality / RCRA violations
    {
        "facility_name": "Tyson Fresh Meats - Dakota City",
        "location": "Dakota City, NE",
        "state": "NE",
        "county": "Dakota",
        "latitude": 42.4155,
        "longitude": -96.4183,
        "violation_type": "Clean Air Act - CAFO Emissions",
        "date": "2023-02-28",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-021",
        "description": "Beef processing facility violated Clean Air Act. Excess emissions of hydrogen sulfide and ammonia from rendering operations. Community odor complaints.",
        "severity": "High",
        "penalty_amount": 850000.0,
    },
    {
        "facility_name": "Triumph Foods",
        "location": "St. Joseph, MO",
        "state": "MO",
        "county": "Buchanan",
        "latitude": 39.7687,
        "longitude": -94.8463,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-07-15",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-022",
        "description": "Pork processing facility with wastewater pretreatment violations. Discharge exceeded BOD and TSS limits. Facility processes over 20,000 hogs per day.",
        "severity": "Medium",
        "penalty_amount": 275000.0,
    },
    {
        "facility_name": "Lincoln Premium Poultry",
        "location": "Fremont, NE",
        "state": "NE",
        "county": "Dodge",
        "latitude": 41.4334,
        "longitude": -96.4981,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-06-10",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-023",
        "description": "Costco-affiliated chicken processing plant with permit violations. Wastewater discharge issues during initial operations. Ammonia exceedances.",
        "severity": "Medium",
        "penalty_amount": 120000.0,
    },
    {
        "facility_name": "Prestage Farms - Eagle Grove",
        "location": "Eagle Grove, IA",
        "state": "IA",
        "county": "Wright",
        "latitude": 42.6644,
        "longitude": -93.9044,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2023-09-20",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-024",
        "description": "Hog processing and CAFO operations with nutrient management violations. Excessive manure application to fields. Nitrate contamination of nearby wells.",
        "severity": "High",
        "penalty_amount": 310000.0,
    },
    {
        "facility_name": "Foster Farms - Livingston",
        "location": "Livingston, CA",
        "state": "CA",
        "county": "Merced",
        "latitude": 37.3869,
        "longitude": -120.7233,
        "violation_type": "Clean Water Act - CAFO",
        "date": "2022-05-18",
        "source": "EPA Enforcement",
        "source_id": "EPA-SEED-025",
        "description": "Poultry processing with wastewater discharge violations in California's Central Valley. Nutrient loading contributing to water quality degradation. History of salmonella issues.",
        "severity": "Medium",
        "penalty_amount": 340000.0,
    },
]

# Real USDA FSIS recalls related to factory farming
FSIS_VIOLATIONS = [
    {
        "facility_name": "Tyson Foods Inc.",
        "location": "Dexter, MO",
        "state": "MO",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2024-01-06",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-001",
        "description": "Tyson Foods recalled approximately 29,819 pounds of chicken nugget products due to possible foreign matter contamination (metal pieces). Class I recall - health hazard situation.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "BrucePac",
        "location": "Woodburn, OR",
        "state": "OR",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2024-10-09",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-002",
        "description": "BrucePac recalled approximately 9,986,245 pounds of ready-to-eat meat and poultry products due to possible Listeria monocytogenes contamination. One of the largest meat recalls in US history.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "Simmons Prepared Foods",
        "location": "Gentry, AR",
        "state": "AR",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-08-03",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-003",
        "description": "Recalled approximately 100,566 pounds of chicken fajita products due to possible foreign matter contamination (bone fragments). Products distributed nationwide.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "Perdue Foods LLC",
        "location": "Salisbury, MD",
        "state": "MD",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-03-25",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-004",
        "description": "Perdue recalled approximately 68,244 pounds of chicken nugget and tender products due to possible metal wire contamination. Class I recall.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "Cargill Meat Solutions Corp.",
        "location": "Fort Morgan, CO",
        "state": "CO",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-10-05",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-005",
        "description": "Recalled approximately 16,243 pounds of ground beef products due to possible E. coli O157:H7 contamination. Products distributed to retail stores nationwide.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "Pilgrim's Pride Corporation",
        "location": "Waco, TX",
        "state": "TX",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-07-14",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-006",
        "description": "Recalled approximately 4,232,579 pounds of ready-to-eat chicken products due to possible Salmonella Enteritidis contamination. Linked to illness cluster.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "Tip Top Poultry",
        "location": "Rockmart, GA",
        "state": "GA",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-01-19",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-007",
        "description": "Recalled cooked chicken products due to possible Listeria monocytogenes contamination. Products distributed to institutional food service operators in multiple states.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "JBS Tolleson Inc.",
        "location": "Tolleson, AZ",
        "state": "AZ",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2022-12-04",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-008",
        "description": "JBS recalled approximately 12,093,271 pounds of non-intact raw beef products due to possible Salmonella Newport contamination. 246 confirmed illnesses across 25 states.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "Serenade Foods",
        "location": "Milford, IN",
        "state": "IN",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-02-02",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-009",
        "description": "Recalled approximately 59,251 pounds of frozen chicken products due to possible Salmonella Enteritidis contamination. Products sold under multiple brand names.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "Wayne Farms LLC",
        "location": "Decatur, AL",
        "state": "AL",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-05-30",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-010",
        "description": "Recalled approximately 585,030 pounds of ready-to-eat chicken breast products due to possible Listeria monocytogenes contamination. Nationwide distribution.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "George's Inc.",
        "location": "Springdale, AR",
        "state": "AR",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-04-12",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-011",
        "description": "Recalled chicken products due to misbranding and undeclared allergens. Products contained milk not declared on label. Distributed to retail and food service.",
        "severity": "Medium",
        "penalty_amount": None,
    },
    {
        "facility_name": "Hormel Foods Corporation",
        "location": "Austin, MN",
        "state": "MN",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-11-08",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-012",
        "description": "Recalled canned pork and chicken products due to possible contamination during production. Underprocessing may allow survival of spoilage organisms.",
        "severity": "Medium",
        "penalty_amount": None,
    },
    {
        "facility_name": "Kenosha Beef International",
        "location": "Kenosha, WI",
        "state": "WI",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-06-25",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-013",
        "description": "Recalled approximately 2,958 pounds of ground beef products due to possible E. coli O157:H7 contamination detected during routine FSIS testing.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "American Foods Group LLC",
        "location": "Green Bay, WI",
        "state": "WI",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2024-03-28",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-014",
        "description": "Recalled approximately 58,281 pounds of ground beef products due to possible E. coli O157:H7 contamination. Products shipped to retail locations in multiple states.",
        "severity": "High",
        "penalty_amount": None,
    },
    {
        "facility_name": "Conagra Brands Inc.",
        "location": "Marshall, MO",
        "state": "MO",
        "county": None,
        "latitude": None,
        "longitude": None,
        "violation_type": "Food Safety Recall - Meat/Poultry",
        "date": "2023-08-20",
        "source": "USDA FSIS Recall",
        "source_id": "FSIS-SEED-015",
        "description": "Recalled Banquet brand chicken strip meals due to possible Salmonella contamination. Over 245,000 pounds of product recalled. Multiple consumer complaints.",
        "severity": "High",
        "penalty_amount": None,
    },
]


def seed_database():
    """Insert seed data into the database."""
    from database import init_db
    init_db()
    conn = get_connection()

    total = 0
    for v in EPA_VIOLATIONS + FSIS_VIOLATIONS:
        try:
            upsert_violation(conn, **v)
            total += 1
        except Exception as e:
            logger.warning(f"Failed to insert seed record: {e}")

    conn.commit()
    conn.close()
    logger.info(f"Seeded {total} violation records.")
    return total


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    count = seed_database()
    print(f"Done. Seeded {count} violations.")
